using System.ComponentModel;
using System.Runtime.InteropServices;
using Shadowsocks.NetworkService.Ipc;
using Shadowsocks.NetworkService.WinDivert;

namespace Shadowsocks.NetworkService.Routing;

internal sealed class WinDivertTransparentRouter : IAsyncDisposable
{
    private const uint MaxPacket = 40 + 65535;
    private readonly FlowRegistry _flows;
    private readonly TransparentTcpRelay _tcpRelay;
    private readonly TransparentUdpRelay _udpRelay;
    private readonly CancellationTokenSource _shutdown = new();
    private nint _handle;
    private Task? _packetLoop;

    public WinDivertTransparentRouter(StartRequest request)
    {
        WinDivertNative.ConfigureDirectory(request.WinDivertDirectory);
        ApplicationPolicy policy = new(request);
        _flows = new FlowRegistry(policy);
        _tcpRelay = new TransparentTcpRelay(_flows, request.LocalProxyHost, request.LocalProxyPort);
        _udpRelay = new TransparentUdpRelay(_flows, request.LocalProxyHost, request.LocalProxyPort);
    }

    public int TcpRedirectPort => _tcpRelay.Port;
    public int UdpRedirectPort => _udpRelay.Port;

    public void Start()
    {
        _tcpRelay.Start();
        _udpRelay.Start();

        // Loopback is deliberately excluded: the transparent relays use the local
        // Shadowsocks SOCKS/UDP endpoint and must not recursively capture themselves.
        _handle = WinDivertNative.Open(
            "outbound and !loopback and (tcp or udp)",
            WinDivertLayer.Network,
            100,
            WinDivertFlags.None);
        if (WinDivertNative.IsInvalidHandle(_handle))
        {
            throw new Win32Exception(Marshal.GetLastPInvokeError(), "WinDivertOpen failed.");
        }

        WinDivertNative.SetParam(_handle, WinDivertParam.QueueLength, 8192);
        WinDivertNative.SetParam(_handle, WinDivertParam.QueueSize, 16 * 1024 * 1024);
        WinDivertNative.SetParam(_handle, WinDivertParam.QueueTime, 1000);
        _packetLoop = Task.Run(PacketLoop);
    }

    private unsafe void PacketLoop()
    {
        byte[] packet = new byte[checked((int)MaxPacket)];
        while (!_shutdown.IsCancellationRequested)
        {
            fixed (byte* packetPtr = packet)
            {
                if (!WinDivertNative.Receive(_handle, packetPtr, MaxPacket, out uint length, out WinDivertAddress address))
                {
                    int error = Marshal.GetLastPInvokeError();
                    if (_shutdown.IsCancellationRequested || error is 995 or 6)
                    {
                        return;
                    }
                    continue;
                }

                if (!PacketView.TryParse(packetPtr, length, out PacketView view))
                {
                    Reinject(packetPtr, length, ref address);
                    continue;
                }

                ushort sourcePort = view.SourcePort;
                ushort destinationPort = view.DestinationPort;
                ushort redirectPort = view.IsTcp
                    ? checked((ushort)_tcpRelay.Port)
                    : checked((ushort)_udpRelay.Port);

                // Response generated by one of the local transparent relays.
                if (sourcePort == redirectPort)
                {
                    if (_flows.TryGetReflected(
                            view.Protocol,
                            view.SourceAddress,
                            destinationPort,
                            view.DestinationAddress,
                            out FlowState? reflected)
                        && reflected is not null)
                    {
                        view.ReflectFromLocal(reflected.Key.RemotePort);
                        address.Outbound = false;
                        WinDivertNative.CalculateChecksums(packetPtr, length, ref address, 0);
                        Reinject(packetPtr, length, ref address);
                    }
                    // Unknown packets from a reserved transparent relay port are not
                    // allowed to escape to the network.
                    continue;
                }

                FlowKey key = new(
                    view.Protocol,
                    view.SourceAddress,
                    sourcePort,
                    view.DestinationAddress,
                    destinationPort);

                // DNS routing is intentionally deferred; bootstrap/local-network
                // protocols remain direct until the DNS policy backend is implemented.
                if (NetworkClassifier.IsInfrastructureTraffic(key))
                {
                    Reinject(packetPtr, length, ref address);
                    continue;
                }

                FlowState state = _flows.GetOrCreate(key);
                switch (state.Route)
                {
                    case RouteAction.Direct:
                    case RouteAction.Default:
                        Reinject(packetPtr, length, ref address);
                        break;
                    case RouteAction.Block:
                        // Drop. A later UX pass may synthesize TCP RST/ICMP unreachable.
                        break;
                    case RouteAction.Proxy:
                        view.ReflectToLocal(redirectPort);
                        address.Outbound = false;
                        WinDivertNative.CalculateChecksums(packetPtr, length, ref address, 0);
                        Reinject(packetPtr, length, ref address);
                        break;
                }
            }
        }
    }

    private unsafe void Reinject(byte* packet, uint length, ref WinDivertAddress address)
    {
        WinDivertNative.Send(_handle, packet, length, out _, in address);
    }

    public async ValueTask DisposeAsync()
    {
        _shutdown.Cancel();
        if (!WinDivertNative.IsInvalidHandle(_handle))
        {
            WinDivertNative.Shutdown(_handle, WinDivertShutdown.Both);
            WinDivertNative.Close(_handle);
            _handle = 0;
        }

        if (_packetLoop is not null)
        {
            try
            {
                await _packetLoop.ConfigureAwait(false);
            }
            catch
            {
            }
        }

        await _tcpRelay.DisposeAsync().ConfigureAwait(false);
        await _udpRelay.DisposeAsync().ConfigureAwait(false);
        _shutdown.Dispose();
    }
}
