//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadowsocks.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shadowsocks.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string addApplicationRuleButton_Content {
            get {
                return ResourceManager.GetString("addApplicationRuleButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Add.
        /// </summary>
        internal static string addButton_Content {
            get {
                return ResourceManager.GetString("addButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add one or more GeoSite URLs (one per line):.
        /// </summary>
        internal static string addGeositeSourcesTextBlock_Text {
            get {
                return ResourceManager.GetString("addGeositeSourcesTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Optional transparent TCP/UDP capture with WinDivert. Enabling it requests administrator rights and downloads WinDivert on demand..
        /// </summary>
        internal static string adminModeDescriptionTextBlock_Text {
            get {
                return ResourceManager.GetString("adminModeDescriptionTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Admin Mode.
        /// </summary>
        internal static string adminModeRadioButton_Content {
            get {
                return ResourceManager.GetString("adminModeRadioButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow clients from LAN.
        /// </summary>
        internal static string AllowClientsFromLAN {
            get {
                return ResourceManager.GetString("AllowClientsFromLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application / path pattern.
        /// </summary>
        internal static string applicationColumnHeaderTextBlock_Text {
            get {
                return ResourceManager.GetString("applicationColumnHeaderTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application routing rules.
        /// </summary>
        internal static string applicationRulesHeaderTextBlock_Text {
            get {
                return ResourceManager.GetString("applicationRulesHeaderTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Cancel.
        /// </summary>
        internal static string cancelButton_Content {
            get {
                return ResourceManager.GetString("cancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string cancelTrafficRoutingButton_Content {
            get {
                return ResourceManager.GetString("cancelTrafficRoutingButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Copy link.
        /// </summary>
        internal static string copyLinkButton_Content {
            get {
                return ResourceManager.GetString("copyLinkButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Credentials (optional).
        /// </summary>
        internal static string CredentialsOptional {
            get {
                return ResourceManager.GetString("CredentialsOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DNS routing policy is reserved in the configuration and routing API, but DNS interception is intentionally not enabled in this revision..
        /// </summary>
        internal static string dnsPolicyPlannedTextBlock_Text {
            get {
                return ResourceManager.GetString("dnsPolicyPlannedTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled.
        /// </summary>
        internal static string enabledColumnHeaderTextBlock_Text {
            get {
                return ResourceManager.GetString("enabledColumnHeaderTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forward Proxy.
        /// </summary>
        internal static string ForwardProxy {
            get {
                return ResourceManager.GetString("ForwardProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address can&apos;t be empty or whitespace..
        /// </summary>
        internal static string ForwardProxyAddressRequired {
            get {
                return ResourceManager.GetString("ForwardProxyAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must provide both username and password..
        /// </summary>
        internal static string ForwardProxyCredentialsPairRequired {
            get {
                return ResourceManager.GetString("ForwardProxyCredentialsPairRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} is out of range (0, 65535]..
        /// </summary>
        internal static string ForwardProxyPortOutOfRange {
            get {
                return ResourceManager.GetString("ForwardProxyPortOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} is out of range (0, 10]..
        /// </summary>
        internal static string ForwardProxyTimeoutOutOfRange {
            get {
                return ResourceManager.GetString("ForwardProxyTimeoutOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One process name or path pattern per line (wildcards * and ? are supported). When a matching application starts, WinDivert is automatically disabled and User Mode is used. Admin Mode is restored automatically after the application exits..
        /// </summary>
        internal static string gameModeDescriptionTextBlock_Text {
            get {
                return ResourceManager.GetString("gameModeDescriptionTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game Mode.
        /// </summary>
        internal static string gameModeHeaderTextBlock_Text {
            get {
                return ResourceManager.GetString("gameModeHeaderTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GeoSite databases used by Local PAC. All listed sources are merged. For each URL Shadowsocks automatically tries &lt;URL&gt;.sha256sum; a missing checksum is not an error..
        /// </summary>
        internal static string geositeSourcesDescriptionTextBlock_Text {
            get {
                return ResourceManager.GetString("geositeSourcesDescriptionTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hotkeys.
        /// </summary>
        internal static string Hotkeys {
            get {
                return ResourceManager.GetString("Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HTTP.
        /// </summary>
        internal static string HTTP {
            get {
                return ResourceManager.GetString("HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move down.
        /// </summary>
        internal static string moveDownButton_Content {
            get {
                return ResourceManager.GetString("moveDownButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move up.
        /// </summary>
        internal static string moveUpButton_Content {
            get {
                return ResourceManager.GetString("moveUpButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No proxy.
        /// </summary>
        internal static string NoProxy {
            get {
                return ResourceManager.GetString("NoProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Not now.
        /// </summary>
        internal static string notNowButton_Content {
            get {
                return ResourceManager.GetString("notNowButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _OK.
        /// </summary>
        internal static string okButton_Content {
            get {
                return ResourceManager.GetString("okButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Online Configuration Delivery.
        /// </summary>
        internal static string OnlineConfigDelivery {
            get {
                return ResourceManager.GetString("OnlineConfigDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning: getting online configuration from plain HTTP sources is NOT secure!.
        /// </summary>
        internal static string OnlineConfigHttpWarning {
            get {
                return ResourceManager.GetString("OnlineConfigHttpWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open logs window.
        /// </summary>
        internal static string OpenLogsWindow {
            get {
                return ResourceManager.GetString("OpenLogsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Register all.
        /// </summary>
        internal static string registerAllButton_Content {
            get {
                return ResourceManager.GetString("registerAllButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register hotkeys at startup.
        /// </summary>
        internal static string RegisterHotkeysAtStartup {
            get {
                return ResourceManager.GetString("RegisterHotkeysAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pre-release.
        /// </summary>
        internal static string ReleaseKindPreRelease {
            get {
                return ResourceManager.GetString("ReleaseKindPreRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Release.
        /// </summary>
        internal static string ReleaseKindRelease {
            get {
                return ResourceManager.GetString("ReleaseKindRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to get release notes.
        /// </summary>
        internal static string ReleaseNotesUnavailable {
            get {
                return ResourceManager.GetString("ReleaseNotesUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to get tag name.
        /// </summary>
        internal static string ReleaseTagUnavailable {
            get {
                return ResourceManager.GetString("ReleaseTagUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        internal static string removeApplicationRuleButton_Content {
            get {
                return ResourceManager.GetString("removeApplicationRuleButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        internal static string removeButton_Content {
            get {
                return ResourceManager.GetString("removeButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        internal static string restoreDefaultButton_Content {
            get {
                return ResourceManager.GetString("restoreDefaultButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Route.
        /// </summary>
        internal static string routeColumnHeaderTextBlock_Text {
            get {
                return ResourceManager.GetString("routeColumnHeaderTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Save.
        /// </summary>
        internal static string saveButton_Content {
            get {
                return ResourceManager.GetString("saveButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string saveTrafficRoutingButton_Content {
            get {
                return ResourceManager.GetString("saveTrafficRoutingButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server Sharing.
        /// </summary>
        internal static string ServerSharing {
            get {
                return ResourceManager.GetString("ServerSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The following sources failed to update:
        ///
        ///.
        /// </summary>
        internal static string sip008UpdateAllFailure {
            get {
                return ResourceManager.GetString("sip008UpdateAllFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully updated all sources!.
        /// </summary>
        internal static string sip008UpdateAllSuccess {
            get {
                return ResourceManager.GetString("sip008UpdateAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update failed. See the logs for more information..
        /// </summary>
        internal static string sip008UpdateFailure {
            get {
                return ResourceManager.GetString("sip008UpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully updated the selected source!.
        /// </summary>
        internal static string sip008UpdateSuccess {
            get {
                return ResourceManager.GetString("sip008UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Skip version.
        /// </summary>
        internal static string skipVersionButton_Content {
            get {
                return ResourceManager.GetString("skipVersionButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SOCKS5.
        /// </summary>
        internal static string SOCKS5 {
            get {
                return ResourceManager.GetString("SOCKS5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch to next server.
        /// </summary>
        internal static string SwitchToNextServer {
            get {
                return ResourceManager.GetString("SwitchToNextServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch to previous server.
        /// </summary>
        internal static string SwitchToPreviousServer {
            get {
                return ResourceManager.GetString("SwitchToPreviousServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timeout (sec).
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle proxy mode.
        /// </summary>
        internal static string ToggleProxyMode {
            get {
                return ResourceManager.GetString("ToggleProxyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle system proxy.
        /// </summary>
        internal static string ToggleSystemProxy {
            get {
                return ResourceManager.GetString("ToggleSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Traffic capture mode.
        /// </summary>
        internal static string trafficCaptureModeHeaderTextBlock_Text {
            get {
                return ResourceManager.GetString("trafficCaptureModeHeaderTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Block.
        /// </summary>
        internal static string trafficRouteBlock {
            get {
                return ResourceManager.GetString("trafficRouteBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Direct.
        /// </summary>
        internal static string trafficRouteDirect {
            get {
                return ResourceManager.GetString("trafficRouteDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy.
        /// </summary>
        internal static string trafficRouteProxy {
            get {
                return ResourceManager.GetString("trafficRouteProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose how traffic is captured and add per-application routing rules. Application rules take priority over the system proxy/PAC decision..
        /// </summary>
        internal static string trafficRoutingDescriptionTextBlock_Text {
            get {
                return ResourceManager.GetString("trafficRoutingDescriptionTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update all.
        /// </summary>
        internal static string updateAllButton_Content {
            get {
                return ResourceManager.GetString("updateAllButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Update.
        /// </summary>
        internal static string updateButton_Content {
            get {
                return ResourceManager.GetString("updateButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please read the release notes carefully. Then decide whether to update..
        /// </summary>
        internal static string updatePromptBody {
            get {
                return ResourceManager.GetString("updatePromptBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An update is available..
        /// </summary>
        internal static string updatePromptTitle {
            get {
                return ResourceManager.GetString("updatePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No administrator rights or driver. Filters applications that actually use the Windows/local HTTP proxy; arbitrary TCP/UDP traffic is not captured..
        /// </summary>
        internal static string userModeDescriptionTextBlock_Text {
            get {
                return ResourceManager.GetString("userModeDescriptionTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Mode.
        /// </summary>
        internal static string userModeRadioButton_Content {
            get {
                return ResourceManager.GetString("userModeRadioButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VersionUpdate.
        /// </summary>
        internal static string VersionUpdate {
            get {
                return ResourceManager.GetString("VersionUpdate", resourceCulture);
            }
        }
    }
}
