using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Shadowsocks.Controller.Traffic;

namespace Shadowsocks.Controller.Service
{
    internal enum DnsCryptTomlPurpose
    {
        Runtime = 0,
        ResolverCatalog = 1,
    }

    internal static class DnsCryptTomlGenerator
    {
        internal const string PublicResolversMinisignKey = "RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3";
        private static readonly Regex ServerNameRegex = new(
            @"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$",
            RegexOptions.CultureInvariant | RegexOptions.Compiled);

        internal static string Generate(
            int listenPort,
            DnsCryptConfig config,
            int? shadowsocksSocks5Port = null,
            DnsCryptTomlPurpose purpose = DnsCryptTomlPurpose.Runtime)
        {
            if (listenPort is < 1 or > 65535)
                throw new ArgumentOutOfRangeException(nameof(listenPort));
            ArgumentNullException.ThrowIfNull(config);
            if (!config.ipv4Servers && !config.ipv6Servers)
                throw new ArgumentException("At least one DNSCrypt address family must be enabled.", nameof(config));
            if (config.routeThroughShadowsocks && (!shadowsocksSocks5Port.HasValue || shadowsocksSocks5Port.Value is < 1 or > 65535))
                throw new ArgumentException(
                    "A valid local Shadowsocks SOCKS5 port is required when DNSCrypt proxy routing is enabled.",
                    nameof(shadowsocksSocks5Port));

            bool catalogMode = purpose == DnsCryptTomlPurpose.ResolverCatalog;
            string[] serverNames = NormalizeServerNames(config.serverNames);
            if (!catalogMode && serverNames.Length == 0)
            {
                throw new ArgumentException(
                    "A DNSCrypt runtime requires at least one resolver selected from the signed catalog.",
                    nameof(config));
            }
            var builder = new StringBuilder(2600);
            builder.AppendLine("# Generated by Shadowsocks Reborn. Do not edit while Shadowsocks is running.");
            if (serverNames.Length > 0)
                builder.Append("server_names = [").Append(string.Join(", ", serverNames.Select(ToTomlLiteral))).AppendLine("]");
            builder.Append("listen_addresses = ['127.0.0.1:").Append(listenPort).AppendLine("']");
            builder.AppendLine("max_clients = 250");
            builder.Append("ipv4_servers = ").AppendLine(ToTomlBoolean(config.ipv4Servers));
            builder.Append("ipv6_servers = ").AppendLine(ToTomlBoolean(config.ipv6Servers));
            // Runtime server_names constrains dnscrypt-proxy to the concrete automatic/manual
            // resolver set selected from the signed catalog before startup.
            builder.AppendLine("dnscrypt_servers = true");
            builder.AppendLine("doh_servers = true");
            builder.AppendLine("odoh_servers = false");
            builder.Append("require_dnssec = ").AppendLine(ToTomlBoolean(config.requireDnssec));
            builder.Append("require_nolog = ").AppendLine(ToTomlBoolean(config.requireNoLog));
            builder.Append("require_nofilter = ").AppendLine(ToTomlBoolean(config.requireNoFilter));
            builder.Append("force_tcp = ").AppendLine(ToTomlBoolean(config.routeThroughShadowsocks));
            if (config.routeThroughShadowsocks)
            {
                builder.Append("proxy = 'socks5://127.0.0.1:").Append(shadowsocksSocks5Port.Value).AppendLine("'");
            }
            builder.AppendLine("http3 = false");
            builder.AppendLine("timeout = 5000");
            builder.AppendLine("keepalive = 30");
            builder.AppendLine("log_level = 2");
            builder.AppendLine("use_syslog = false");
            builder.AppendLine("pqdnscrypt = true");
            if (catalogMode)
            {
                // Resolver catalog refresh is an explicit maintenance operation. dnscrypt-proxy
                // may need one-shot plaintext bootstrap DNS before a signed resolver list exists.
                // Active DNS runtimes never receive these bootstrap resolvers.
                builder.AppendLine("bootstrap_resolvers = ['9.9.9.11:53', '8.8.8.8:53']");
            }
            else
            {
                // Active DNS must never depend on plaintext bootstrap DNS. Automatic/Manual
                // runtimes reuse the signed resolver cache produced by the catalog loader.
                builder.AppendLine("bootstrap_resolvers = []");
            }
            builder.AppendLine("ignore_system_dns = true");
            builder.AppendLine("netprobe_timeout = 0");
            builder.AppendLine("netprobe_address = '1.1.1.1:443'");
            builder.AppendLine("block_ipv6 = false");
            builder.AppendLine("block_unqualified = true");
            builder.AppendLine("block_undelegated = true");
            builder.AppendLine("cache = true");
            builder.AppendLine("cache_size = 4096");
            builder.AppendLine("enable_hot_reload = false");
            builder.AppendLine();
            AppendPublicResolverSource(builder);
            return builder.ToString();
        }

        internal static bool RuntimeUsesPlaintextBootstrap(string toml)
        {
            if (string.IsNullOrWhiteSpace(toml))
                return true;
            return !toml.Contains("bootstrap_resolvers = []", StringComparison.Ordinal)
                || !toml.Contains("ignore_system_dns = true", StringComparison.Ordinal);
        }

        private static void AppendPublicResolverSource(StringBuilder builder)
        {
            builder.AppendLine("[sources]");
            builder.AppendLine("[sources.public-resolvers]");
            builder.AppendLine("urls = [");
            builder.AppendLine("  'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md',");
            builder.AppendLine("  'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md',");
            builder.AppendLine("  'https://cdn.jsdelivr.net/gh/DNSCrypt/dnscrypt-resolvers@master/v3/public-resolvers.md'");
            builder.AppendLine("]");
            builder.AppendLine("cache_file = 'public-resolvers.md'");
            builder.Append("minisign_key = '").Append(PublicResolversMinisignKey).AppendLine("'");
            builder.AppendLine("refresh_delay = 73");
            builder.AppendLine("prefix = ''");
        }

        internal static string[] NormalizeServerNames(IEnumerable<string> serverNames)
        {
            if (serverNames is null)
                return [];

            var result = new List<string>();
            var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (string candidate in serverNames)
            {
                string value = candidate?.Trim();
                if (string.IsNullOrWhiteSpace(value))
                    continue;
                if (!ServerNameRegex.IsMatch(value))
                    throw new ArgumentException($"DNSCrypt resolver name '{value}' contains unsupported characters.", nameof(serverNames));
                if (seen.Add(value))
                    result.Add(value);
            }
            return result.ToArray();
        }

        private static string ToTomlBoolean(bool value) => value ? "true" : "false";
        private static string ToTomlLiteral(string value) => "'" + value + "'";
    }
}
